version: "3.0"
networks:
    bls:

services:
    parser:
        build: ./c/parser/
        networks:
            - bls
    memcached1:
        image: memcached:latest
        networks:
            - bls
    memcached2:
        image: memcached:latest
        networks:
            - bls
    memcached3:
        image: memcached:latest
        networks:
            - bls
    cassandra:
        image: cassandra:latest
        networks:
            - bls
    web-client:
        build: ./c/web/client/
        networks: 
            - bls
        ports: 
            - "1234:80"

    web-server:
        build: ./c/web/server/
        networks: 
            - bls
        ports: 
            - "12345:80"



